name: united_end2end
description: "United End2End Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  dropdown_button2: ^3.0.0-beta.22
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.8.0

# dependency_overrides:

flutter_gen:
  output: lib/config/gen/ # Optional (default: lib/gen/)
  line_length: 100 # Optional (default: 80)

  # Optional
  integrations:
    image: false
    flutter_svg: false
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: camel-case
      class_name: Assets
    exclude: []

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logo/
  # fonts:
  #   - family: Comfortaa
  #     fonts:
  #       - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
  #         weight: 400
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
